// fsm.js
exports.allowedTransitions = {
    REQUESTED: ["SEARCHING"],
    SEARCHING: ["DRIVER_ASSIGNED", "CANCELLED_BY_RIDER", "EXPIRED"],
    DRIVER_ASSIGNED: ["DRIVER_ARRIVING", "CANCELLED_BY_DRIVER"],
    DRIVER_ARRIVING: ["IN_PROGRESS"],
    IN_PROGRESS: ["COMPLETED"],
  };
  